example.com:
  api-key: YOUR_API_KEY
  records-to-update:
    - "example.com"
    - "subdomain.example.com"
    - "foo.example.com"

example.net:
  api-key: YOUR_API_KEY
  records-to-update:
    - "test.net"
    - "foo.test.net"
